{% set name = "teensytoany" %}
{% set version = "0.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9a4e8b0e7d35b0a04061c9479937bab39fd01fb5adc0e64dae2b63854ea7b8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4
    - pip
  run:
    - python >=3.7,<4
    - pyserial
    - packaging

test:
  imports:
    - teensytoany

about:
  home: https://github.com/ramonaoptics/python-teensytoany/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Pythonic way to control the TeensyToAny debugging board

extra:
  recipe-maintainers:
    - hmaarrfk
