{% set name = "teensytoany" %}
{% set version = "0.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75388752d68a779477ea1dfad92b6698bbc1df9839759a73409472af3bce2876

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pyserial

test:
  imports:
    - teensytoany

about:
  home: https://github.com/ramonaoptics/python-teensytoany/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Pythonic way to control the TeensyToAny debugging board

extra:
  recipe-maintainers:
    - hmaarrfk
