{% set name = "teensytoany" %}
{% set version = "0.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e78a0a00f5a40e7e12a035dd6ca9a82174a3792f8bcee30e5944b7207e12ed4c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4
    - pip
  run:
    - python >=3.7,<4
    - pyserial
    - packaging

test:
  imports:
    - teensytoany

about:
  home: https://github.com/ramonaoptics/python-teensytoany/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Pythonic way to control the TeensyToAny debugging board

extra:
  recipe-maintainers:
    - hmaarrfk
